#!/usr/bin/env bash
# Bash script to install and configure Nginx on Ubuntu 16.04

# Update the package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx start
