#!/usr/bin/env bash
# Script for duplicating web-01 to web-02
# An upgraded version from the web-server scripts...

# Uncomment to see the script run in action
#set -x

echo -e "Updating and doing some minor checks...\n"

function install_package() {
    command -v "$1" &> /dev/null

    if [ $? -ne 0 ]; then
        echo -e "    Installing: $1\n"
        sudo apt-get update -y -qq && \
        sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "    $1 is already installed.\n"
    fi
}

install_package nginx # Install nginx

echo -e "\nSetting up some minor stuff...\n"

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership of website files for easy editing
if [ -d "/var/www" ]; then
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
else
    sudo mkdir -p /var/www
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
fi

# Create directories if not present
for dir in /var/www/{html,error}; do
    if ! [ -d "$dir" ]; then
        mkdir -p "$dir"
    fi
done

# Create a new index
echo "Hello World!" > /var/www/html/index.html

# Create a new error page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# Backup default server config file
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup

server_config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html
        server_name_;
        add_header X-Served-By \$hostname;
        location / {
            try_files \$uri \$uri/ =404;
        }
        if (\$request_filename ~ redirect_me){
            rewrite ^ https://th3-gr00t.tk/ permanent;
        }
        error_page 404 /error_404.html;
        location = /error_404.html {
            internal;
        }
}"

# Write the configuration to Nginx file
echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default

# Check if Nginx is running and start or restart
if [ "$(pgrep -c nginx)" -le 0 ]; then
    sudo service nginx start
else
    sudo service nginx restart
fi
