#!/usr/bin/env bash
#Installs and configures HAproxy in a load balancer server

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8

# Update package lists
sudo apt update

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 226597-web-01:80 check
    server web02 226597-web-02:80 check
EOF

# Enable HAProxy init script
sudo systemctl enable haproxy

# Restart HAProxy service
sudo systemctl restart haproxy
