#!/usr/bin/env bash
# Check if the password argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <mysql_password>"
    exit 1
fi

# Set the password for MySQL root user
mysql_password=$1

# Define backup file names
backup_sql="backup.sql"
backup_date="$(date +'%d-%m-%Y')"
backup_tar="backup_$backup_date.tar.gz"

# Create MySQL dump
if mysqldump -u root -p"$mysql_password" --all-databases > "$backup_sql"; then
    echo "MySQL dump failed. Exiting."
    exit 1
fi

# Check if MySQL dump was successful
#if [ $? -ne 0 ]; then
#    echo "MySQL dump failed. Exiting."
#    exit 1
#fi

# Compress MySQL dump
if tar -czf "$backup_tar" "$backup_sql"; then
    echo "Compression failed. Exiting."
    exit 1
fi

# Check if compression was successful
#if [ $? -ne 0 ]; then
#    echo "Compression failed. Exiting."
#    exit 1
#fi

# Remove MySQL dump file
rm "$backup_sql"

echo "Backup completed successfully. Archive: $backup_tar"
