#!/usr/bin/env bash
# Script that displays "To infinity and beyond" indefinitely with a 2-second delay.

# Use a while loop to print the message and introduce a 2-second delay between each iteration.
while true; do
  echo "To infinity and beyond"
  sleep 2
done
