#!/usr/bin/env bash
# Script that stops the 4-to_infinity_and_beyond process.

# Use the kill command to find and terminate the 4-to_infinity_and_beyond process.
kill "$(pgrep -f 4-to_infinity_and_beyond)"
