#!/usr/bin/env bash
# Script that stops the 4-to_infinity_and_beyond process.

# Use the pkill command to find and terminate the 4-to_infinity_and_beyond process.
pkill -f '4-to_infinity_and_beyond'

echo "Terminated"
