#!/usr/bin/env bash
# Script to display "To infinity and beyond" indefinitely
# with a 2-second pause between each iteration.
# The script also responds to SIGTERM signal with "I am invincible!!!"

while true
do 
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
