#!/usr/bin/env bash
# This script displays numbers from 1 to 100 following the FizzBuzz rules

# Use the for loop to display the numbers in a list format
for ((i=1; i<=100; i++)); do
    if ((i % 3 == 0)) && ((i % 5 == 0)); then
        echo "FizzBuzz"
    elif ((i % 3 == 0)); then
        echo "Fizz"
    elif ((i % 5 == 0)); then
        echo "Buzz"
    else
        echo "$i"
    fi
done
