#!/usr/bin/env bash

# Displays a story with each line of /etc/passwd.

input="/etc/passwd"
while IFS=: read -r username password uid gid description home shell
do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $description"
done < "$input"
