#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

# Initialize variables for hours and minutes
hour=0
minute=1

# Write the while loop to display the clock
while [ "$hour" -lt 12 ]; do
    echo "Hour: $hour"

    while [ "$minute" -le 59 ]; do
        echo "$minute"
        ((minute++))
    done

    ((hour++))
    minute=0
done
