#!/usr/bin/env bash
# Install ufw
sudo apt-get update
sudo apt-get install ufw -y

# Configure ufw to block all incoming traffic except for SSH, HTTPS, and HTTP
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable ufw
sudo ufw enable
