#!/usr/bin/env bash
# Run Nginx as Nginx

# Modify nginx.conf to run Nginx as nginx user
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Update default server block to listen on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Restart Nginx service
service nginx restart
